exclude: [rakefile, lowbrow, f4index.html, mp3]
plugins_dir: ./_plugins
siteTitle: Adam Cooper Wood
future: false
relative_permalinks: false
url: http://acdubs.com
sitemap:
    exclude:
        - "404"