exclude: [rakefile, lowbrow, f4index.html, mp3, Gemfile]
plugins_dir: ./_plugins
siteTitle: Adam Wood Burlington VT Web Design Development
future: false
relative_permalinks: false
url: http://acdubs.com
tech: [PHP, MySQL, CSS, SASS, Javascript, Python, Ruby, Grunt, Jekyll, Wordpress, Drupal, Rails, Foundation, Bootstrap, GIT, SVN]
apps: [Photoshop, Illustrator, After Effects, Premiere, Arduino IDE, Logic Pro, Pro Tools]
gems:
  - jekyll-sitemap